import type { ImpactMetric, ImpactProject, JournalPost, Product } from "@/types/content";

export const products: Product[] = [
  {
    id: "roosa-standard",
    slug: "pink-toilet-paper",
    name: "ROOSA Pink Toilet Paper",
    eyebrow: "The everyday original",
    description: "A product-first presentation of ROOSA’s signature pink paper. Final specifications will be supplied from Shopify and approved product documentation.",
    displayPrice: "[PRODUCT_PRICE]",
    currency: "CHF",
    image: "/media/products/pink-pack.jpg",
    alternateImage: "/media/products/pink-roll.webp",
    packSize: "[PACK_SIZE]",
    rolls: "[ROLL_COUNT]",
    sheets: "[SHEETS_PER_ROLL]",
    ply: "[PLY_COUNT]",
    material: "[PAPER_MATERIAL]",
    origin: "[MANUFACTURING_COUNTRY]",
    certification: "[CERTIFICATION_STATUS]",
    inStock: null,
    purchaseMode: "one-time",
  },
  {
    id: "roosa-family",
    slug: "family-bundle",
    name: "ROOSA Family Bundle",
    eyebrow: "More paper, fewer deliveries",
    description: "A larger bundle for households. Availability, final pack size and price are managed by Shopify.",
    displayPrice: "[BUNDLE_PRICE]",
    currency: "CHF",
    image: "/media/products/pink-pack.jpg",
    alternateImage: "/media/products/pink-roll.webp",
    packSize: "[BUNDLE_PACK_SIZE]",
    rolls: "[BUNDLE_ROLL_COUNT]",
    sheets: "[SHEETS_PER_ROLL]",
    ply: "[PLY_COUNT]",
    material: "[PAPER_MATERIAL]",
    origin: "[MANUFACTURING_COUNTRY]",
    certification: "[CERTIFICATION_STATUS]",
    inStock: null,
    purchaseMode: "one-time",
  },
  {
    id: "roosa-subscription",
    slug: "subscription",
    name: "ROOSA Repeat Delivery",
    eyebrow: "Optional subscription",
    description: "A recurring option that will only be enabled when frequency, discount and cancellation terms are confirmed.",
    displayPrice: "[SUBSCRIPTION_PRICE]",
    currency: "CHF",
    image: "/media/products/pink-roll.webp",
    alternateImage: "/media/products/embossed-roll.webp",
    packSize: "[SUBSCRIPTION_PACK_SIZE]",
    rolls: "[ROLL_COUNT]",
    sheets: "[SHEETS_PER_ROLL]",
    ply: "[PLY_COUNT]",
    material: "[PAPER_MATERIAL]",
    origin: "[MANUFACTURING_COUNTRY]",
    certification: "[CERTIFICATION_STATUS]",
    inStock: null,
    purchaseMode: "subscription",
  },
];

export const impactMetrics: ImpactMetric[] = [
  { value: "[TOTAL_CONTRIBUTIONS]", label: "Contributions transferred", period: "[REPORTING_PERIOD]", source: "[REPORT_URL]" },
  { value: "[PROJECT_COUNT]", label: "Projects supported", period: "[REPORTING_PERIOD]", source: "[REPORT_URL]" },
  { value: "[PARTNER_COUNT]", label: "Verified partners", period: "[REPORTING_PERIOD]", source: "[REPORT_URL]" },
];

export const projects: ImpactProject[] = [
  {
    slug: "featured-project",
    name: "[PROJECT_NAME]",
    partner: "[PARTNER_NAME]",
    location: "[PROJECT_LOCATION]",
    period: "[REPORTING_PERIOD]",
    objective: "[APPROVED_PROJECT_OBJECTIVE]",
    result: "[DOCUMENTED_PROJECT_RESULT]",
    contribution: "[CONTRIBUTION_AMOUNT]",
    status: "active",
    image: "/media/journal/family-support.jpg",
  },
];

export const journalPosts: JournalPost[] = [
  { slug: "a-small-fighter", title: "A small fighter", summary: "A migrated ROOSA story awaiting editorial and safeguarding review.", date: "2026-05-26", category: "Impact", image: "/media/journal/little-fighter.jpg" },
  { slug: "working-for-a-good-cause", title: "Working for a good cause", summary: "Field notes from the ROOSA team, restructured for the new journal.", date: "2026-05-13", category: "Company", image: "/media/journal/field-team.jpg" },
  { slug: "support-for-families", title: "Support for families", summary: "A project update that will link to the structured impact record once verified.", date: "2026-04-21", category: "Partnerships", image: "/media/journal/family-support.jpg" },
];
