import { PageHero, requireLocale, routeMetadata, styles, type LocaleParams } from "../editorial";

export const metadata = routeMetadata("About", "The intended ROOSA brand, company and impact-partner story, with unapproved details clearly marked.");

export default async function AboutPage({ params }: { params: LocaleParams }) {
  await requireLocale(params);
  return <main className={styles.page}>
    <PageHero eyebrow="About ROOSA" title="An everyday object, made impossible to ignore." lead="ROOSA pairs distinctive pink toilet paper with a visible child-protection message. The original packaging features Carsten Stahl and named organisations rather than hiding purpose in small print." image="/media/v4/brand-lifestyle-editorial.webp" imageAlt="An adult carrying a stack of pink ROOSA rolls through a colourful home" />
    <section className={`${styles.section} ${styles.sectionPink}`}><div className={`${styles.sectionInner} ${styles.feature}`}><div><p className="eyebrow">Origin</p><h2>The story starts with a simple question.</h2></div><div><p>Can a household essential carry a serious social message without losing sight of product quality?</p><p>ROOSA answers with unmistakable colour, original campaign packaging and a reporting structure designed to connect purchase, partner and evidence.</p></div></div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.grid2}><article className={styles.card}><p className="eyebrow">Campaign voice</p><h3>Carsten Stahl on the original pack.</h3><p>The authentic product photograph is used throughout v4 so the campaign figure and child-protection message remain part of the product identity.</p></article><article className={styles.card}><p className="eyebrow">Why pink</p><h3>A visible break from the category.</h3><p>Pink makes an anonymous household category recognisable. Product specifications remain separate, testable facts.</p></article></div></div></section>
    <section className={`${styles.section} ${styles.sectionImpact}`}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Why child protection</p><div><h2>Care needs structure, not sentiment alone.</h2><p>ROOSA’s reporting model prioritises named partners, defined periods and evidence while avoiding exposed child identities, sensationalised harm and unverified beneficiary claims.</p></div></div></div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Operating model</p><div><h2>Who does what.</h2><p>The demo separates the customer experience, commercial operations, partner evidence and distribution records so production ownership can be connected cleanly.</p></div></div><div className={styles.grid4}><article className={styles.card}><p className="eyebrow">Consumer brand</p><h3>ROOSA</h3><p>Product, customer experience and public reporting.</p></article><article className={styles.card}><p className="eyebrow">Commerce</p><h3>Demo order service</h3><p>Simulated inventory, cart totals and orders with no payment collection.</p></article><article className={styles.card}><p className="eyebrow">Impact records</p><h3>Named partner model</h3><p>Programme delivery, period and evidence fields remain distinct from sales data.</p></article><article className={styles.card}><p className="eyebrow">Distribution</p><h3>B2B enquiry flow</h3><p>Wholesale, fulfilment and regional requirements captured for follow-up.</p></article></div></div></section>
    <section className={`${styles.section} ${styles.sectionDark}`}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Values</p><div><h2>Useful standards for daily decisions.</h2></div></div><div className={styles.grid3}>{[["Specificity","Make claims with a period, source and owner."],["Dignity","Protect people before promoting stories."],["Accountability","Publish what can be supported and correct what changes."]].map(([title,body]) => <article className={`${styles.card} ${styles.darkCard}`} key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.grid2}><div><p className="eyebrow">People</p><h2 className="heading-xl">Real field photography, carefully used.</h2><p className={styles.placeholder}>V4 restores the original team and community images while generated photography is reserved for product presentation.</p></div><div><p className="eyebrow">V4 milestones</p><ul className={styles.list}><li><span>01</span><strong>Authentic packaging and Carsten Stahl restored</strong></li><li><span>02</span><strong>Transparent pink and white roll system added</strong></li><li><span>03</span><strong>Demo cart, totals and checkout service connected</strong></li></ul></div></div></div></section>
  </main>;
}
