import Image from "next/image";
import Link from "next/link";
import { FAQAccordion } from "@/components/v2-editorial/FAQAccordion";
import { impactMetrics, projects } from "@/lib/content";
import { localizedPath } from "@/lib/i18n";
import { PageHero, requireLocale, routeMetadata, styles, type LocaleParams } from "../editorial";

export const metadata = routeMetadata("Impact", "How ROOSA intends to connect each purchase with documented child-protection work.");

const mechanism = [
  ["Customer purchase", "A customer buys a ROOSA product through an approved sales channel."],
  ["ROOSA allocation", "The demo records CHF 1.00 per simulated pack and groups it into a reporting period."],
  ["Partner organisation", "Funds are transferred to a named, due-diligenced organisation."],
  ["Named project", "The allocation is connected to a structured project record."],
  ["Documented outcome", "Approved evidence and methodology describe what the project delivered."],
];

export default async function ImpactPage({ params }: { params: LocaleParams }) {
  const locale = await requireLocale(params);
  return <main className={styles.page}>
    <PageHero eyebrow="Impact report · demo data" title="A contribution should leave a paper trail." lead="This demo shows the intended route from product purchase to allocation, partner, project and documented outcome. Simulated values are labelled throughout and are not public impact claims." image="/media/v4/impact-hands-editorial.webp" imageAlt="Adult volunteers preparing colourful care and school kits" />
    <section className={`${styles.section} ${styles.sectionImpact}`}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Contribution mechanism</p><div><h2>From purchase to evidence.</h2><p>Each step is intended to be attributable, reviewable and reported for a defined period.</p></div></div><div className={styles.flow}>{mechanism.map(([title, body]) => <div className={styles.flowStep} key={title}><strong>{title}</strong><p>{body}</p></div>)}</div></div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Illustrative period</p><div><h2>January–June 2026 simulation</h2><p>A complete sample reporting period, ready to be replaced by reconciled production data.</p></div></div><div className={styles.grid3}>{impactMetrics.map((metric) => <article className={styles.card} key={metric.label}><span className={styles.metricValue}>{metric.value}</span><h3>{metric.label}</h3><p className={styles.meta}>Period: {metric.period}</p><p className={styles.meta}>Source: {metric.source}</p></article>)}</div></div></section>
    <section className={`${styles.section} ${styles.sectionPink}`}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Project database</p><div><h2>Named work, structured records.</h2><p>The sample record demonstrates the final information architecture without presenting simulated outcomes as fact.</p></div></div>{projects.map((project) => <article className={styles.project} key={project.slug}><div className={styles.projectImage}><Image src={project.image} alt="General project setting documented for ROOSA impact reporting" fill sizes="(max-width: 767px) 100vw, 55vw" /></div><div className={styles.projectBody}><div><span className={styles.pill}>{project.status}</span><h3>{project.name}</h3><p>{project.objective}</p></div><div><p className={styles.meta}>{project.partner} · {project.location} · {project.period}</p><div className={styles.actions}><Link className="button button--primary" href={localizedPath(locale, `/impact/projects/${project.slug}`)}>View demo record</Link></div></div></div></article>)}</div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Partners</p><div><h2>Work through accountable organisations.</h2><p>The original pack visibly names child-protection organisations. Production reporting will add agreement scope, period and due-diligence information.</p></div></div><div className={styles.logos}><div className={styles.logo}><Image src="/media/impact/partner-kinderschutz.svg" alt="Kinderschutz Schweiz" width={220} height={80} /></div><div className={styles.logo}><Image src="/media/impact/partner-stoppt-mobbing.svg" alt="Stoppt Mobbing" width={220} height={80} /></div></div></div></section>
    <section className={`${styles.section} ${styles.sectionDark}`} id="methodology"><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Methodology</p><div><h2>Define, transfer, reconcile, publish.</h2><p>The demo models the controls production reporting needs: a contribution basis, transfer timing, evidence thresholds, corrections and named ownership.</p></div></div><div className={styles.grid3}><div className={`${styles.card} ${styles.darkCard}`}><p className="eyebrow">01 · Basis</p><h3>CHF 1.00 per demo pack</h3><p>Illustrative unit used only to test calculations and reporting layouts.</p></div><div className={`${styles.card} ${styles.darkCard}`}><p className="eyebrow">02 · Controls</p><h3>Monthly demo reconciliation</h3><p>Cart records roll into a simulated period before review and publication.</p></div><div className={`${styles.card} ${styles.darkCard}`}><p className="eyebrow">03 · Evidence</p><h3>Named record and source</h3><p>Every production claim will require a partner, period, source and review owner.</p></div></div></div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.feature}><div><p className="eyebrow">Reports & downloads</p><h2>The reporting slot is ready.</h2></div><div><p>The production connection will publish a dated PDF with its period, summary, file size and review owner. Demo values remain on-screen only.</p><div className={styles.actions}><button className="button button--secondary" type="button" disabled>Production report not connected</button></div></div></div></div></section>
    <section className={`${styles.section} ${styles.sectionPink}`}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Governance</p><div><h2>Separate commercial activity from impact evidence.</h2><p>ROOSA presents the consumer product and reporting interface. Production launch requires the operating entity, partner agreements and distribution relationships to be inserted from signed records.</p></div></div><div className={styles.placeholder}>Demo control: commercial data and impact evidence remain separate; simulated figures cannot be published as verified outcomes.</div></div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">FAQ</p><div><h2>Questions deserve specific answers.</h2></div></div><FAQAccordion items={[{question:"How much does each purchase contribute?",answer:"The demo uses CHF 1.00 per pack solely to exercise the cart and reporting interface. Replace it with the signed production rule before launch."},{question:"Who receives the contribution?",answer:"Each production transfer will connect to a named partner, project and reporting period. The current records are labelled simulations."},{question:"How are outcomes verified?",answer:"Production outcomes require partner documentation, a defined measurement period and a named review owner."},{question:"Can I download an impact report?",answer:"The download slot is ready, but it remains disabled until the first reconciled production report is connected."}]} /></div></section>
  </main>;
}
