import Image from "next/image";
import Link from "next/link";
import { FAQAccordion } from "@/components/v2-editorial/FAQAccordion";
import { impactMetrics, projects } from "@/lib/content";
import { localizedPath } from "@/lib/i18n";
import { PageHero, requireLocale, routeMetadata, styles, type LocaleParams } from "../editorial";

export const metadata = routeMetadata("Impact", "How ROOSA intends to connect each purchase with documented child-protection work.");

const mechanism = [
  ["Customer purchase", "A customer buys a ROOSA product through an approved sales channel."],
  ["ROOSA allocation", "The approved contribution rule and accounting period will be published here."],
  ["Partner organisation", "Funds are transferred to a named, due-diligenced organisation."],
  ["Named project", "The allocation is connected to a structured project record."],
  ["Documented outcome", "Approved evidence and methodology describe what the project delivered."],
];

export default async function ImpactPage({ params }: { params: LocaleParams }) {
  const locale = await requireLocale(params);
  return <main className={styles.page}>
    <PageHero eyebrow="Impact report" title="A contribution should leave a paper trail." lead="ROOSA is building a transparent route from product purchase to partner, project and documented outcome. Unapproved figures remain explicit placeholders on this implementation." image="/media/journal/family-support.jpg" imageAlt="ROOSA project team supporting families" />
    <section className={`${styles.section} ${styles.sectionImpact}`}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Contribution mechanism</p><div><h2>From purchase to evidence.</h2><p>Each step is intended to be attributable, reviewable and reported for a defined period.</p></div></div><div className={styles.flow}>{mechanism.map(([title, body]) => <div className={styles.flowStep} key={title}><strong>{title}</strong><p>{body}</p></div>)}</div></div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Current period</p><div><h2>reporting period pending approval</h2><p>The current reporting period, closing date and publication cadence are awaiting operational approval.</p></div></div><div className={styles.grid3}>{impactMetrics.map((metric) => <article className={styles.card} key={metric.label}><span className={styles.metricValue}>{metric.value}</span><h3>{metric.label}</h3><p className={styles.meta}>Period: {metric.period}</p><p className={styles.meta}>Source: {metric.source}</p></article>)}</div></div></section>
    <section className={`${styles.section} ${styles.sectionPink}`}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Project database</p><div><h2>Named work, structured records.</h2><p>Filtering will be introduced when there are enough approved projects to make it useful.</p></div></div>{projects.map((project) => <article className={styles.project} key={project.slug}><div className={styles.projectImage}><Image src={project.image} alt="General project setting documented for ROOSA impact reporting" fill sizes="(max-width: 767px) 100vw, 55vw" /></div><div className={styles.projectBody}><div><span className={styles.pill}>{project.status}</span><h3>{project.name}</h3><p>{project.objective}</p></div><div><p className={styles.meta}>{project.partner} · {project.location} · {project.period}</p><div className={styles.actions}><Link className="button button--primary" href={localizedPath(locale, `/impact/projects/${project.slug}`)}>View project record</Link></div></div></div></article>)}</div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Partners</p><div><h2>Work through accountable organisations.</h2><p>Logos identify intended partner records only; relationship descriptions and due-diligence statements require approval.</p></div></div><div className={styles.logos}><div className={styles.logo}><Image src="/media/impact/partner-kinderschutz.svg" alt="Kinderschutz Schweiz" width={220} height={80} /></div><div className={styles.logo}><Image src="/media/impact/partner-stoppt-mobbing.svg" alt="Stoppt Mobbing" width={220} height={80} /></div></div></div></section>
    <section className={`${styles.section} ${styles.sectionDark}`} id="methodology"><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Methodology</p><div><h2>Define, transfer, reconcile, publish.</h2><p>The final methodology must document the contribution basis, transfer timing, restricted versus unrestricted funds, evidence thresholds, corrections and approval ownership.</p></div></div><div className={styles.grid3}><div className={`${styles.card} ${styles.darkCard}`}><p className="eyebrow">01 · Basis</p><h3>contribution rule pending approval</h3><p>Exact unit, percentage, exclusions and tax treatment awaiting finance approval.</p></div><div className={`${styles.card} ${styles.darkCard}`}><p className="eyebrow">02 · Controls</p><h3>reconciliation process pending approval</h3><p>Owner, schedule and sign-off evidence awaiting governance approval.</p></div><div className={`${styles.card} ${styles.darkCard}`}><p className="eyebrow">03 · Evidence</p><h3>evidence standard pending approval</h3><p>Partner documentation and outcome verification criteria awaiting approval.</p></div></div></div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.feature}><div><p className="eyebrow">Reports & downloads</p><h2>No approved report is available yet.</h2></div><div><p>When an approved PDF exists, this record will show its reporting year, summary, file size and publication date.</p><div className={styles.actions}><button className="button button--secondary" type="button" disabled>Download report year pending approval report</button></div></div></div></div></section>
    <section className={`${styles.section} ${styles.sectionPink}`}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Governance</p><div><h2>Separate commercial activity from impact evidence.</h2><p>ROOSA is the consumer brand. operating company pending approval manages commercial operations; impact partner pending approval delivers approved work; distribution partners pending approval support distribution. Exact legal and governance relationships await approval.</p></div></div><div className={styles.placeholder}>Governance owner, review frequency and escalation process: governance details pending approval.</div></div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">FAQ</p><div><h2>Questions deserve specific answers.</h2></div></div><FAQAccordion items={[{question:"How much does each purchase contribute?",answer:"The approved contribution basis is not yet published. It will appear here as contribution rule pending approval rather than as an estimated claim."},{question:"Who receives the contribution?",answer:"Each approved transfer will be connected to a named partner and reporting period in the project database."},{question:"How are outcomes verified?",answer:"The final evidence standard, partner documentation requirements and review owner are awaiting governance approval."},{question:"Can I download an impact report?",answer:"Not yet. Downloads stay disabled until an approved PDF and its publication details are available."}]} /></div></section>
  </main>;
}
