import type { ImpactMetric, ImpactProject, Product } from "@/types/content";

export const products: Product[] = [
  {
    id: "roosa-standard",
    slug: "pink-toilet-paper",
    name: "ROOSA Pink Toilet Paper",
    eyebrow: "The everyday original",
    description: "ROOSA’s signature eight-roll pink paper pack, featuring Carsten Stahl and the original child-protection message. Commerce values are simulated.",
    displayPrice: "CHF 12.90 · demo",
    currency: "CHF",
    image: "/media/products/pink-pack.jpg",
    alternateImage: "/media/products/pink-roll.webp",
    packSize: "8-roll pack",
    rolls: "8",
    sheets: "150 · demo catalog value",
    ply: "3",
    material: "Soft embossed tissue · demo copy",
    origin: "Switzerland · demo catalog value",
    certification: "Document library demo",
    inStock: true,
    purchaseMode: "one-time",
  },
  {
    id: "roosa-family",
    slug: "family-bundle",
    name: "ROOSA Family Bundle",
    eyebrow: "More paper, fewer deliveries",
    description: "A larger bundle for households. Availability, final pack size and price are managed by Shopify.",
    displayPrice: "CHF 39.90 · demo",
    currency: "CHF",
    image: "/media/products/roll-detail-4.webp",
    alternateImage: "/media/products/roll-detail-5.webp",
    packSize: "4 × 8-roll packs",
    rolls: "32",
    sheets: "150 per roll · demo catalog value",
    ply: "3",
    material: "Soft embossed tissue · demo copy",
    origin: "Switzerland · demo catalog value",
    certification: "Document library demo",
    inStock: true,
    purchaseMode: "one-time",
  },
  {
    id: "roosa-subscription",
    slug: "subscription",
    name: "ROOSA Repeat Delivery",
    eyebrow: "Optional subscription",
    description: "A simulated recurring option with four- or eight-week delivery intervals. No subscription is created.",
    displayPrice: "CHF 11.60 · demo delivery",
    currency: "CHF",
    image: "/media/products/pink-roll.webp",
    alternateImage: "/media/products/roll-single.webp",
    packSize: "8-roll delivery",
    rolls: "8",
    sheets: "150 per roll · demo catalog value",
    ply: "3",
    material: "Soft embossed tissue · demo copy",
    origin: "Switzerland · demo catalog value",
    certification: "Document library demo",
    inStock: true,
    purchaseMode: "subscription",
  },
];

export const impactMetrics: ImpactMetric[] = [
  { value: "CHF 12.4k · demo", label: "Contributions", period: "Jan–Jun 2026 simulation", source: "ROOSA demo dataset · no funds transferred" },
  { value: "8 · demo", label: "Project records", period: "Jan–Jun 2026 simulation", source: "ROOSA demo dataset" },
  { value: "5 · demo", label: "Partner records", period: "Jan–Jun 2026 simulation", source: "ROOSA demo dataset" },
];

export const projects: ImpactProject[] = [
  {
    slug: "featured-project",
    name: "Family support record · demo",
    partner: "Bündnis Kinderschutz Schweiz · demo record",
    location: "Switzerland",
    period: "Jan–Jun 2026 simulation",
    objective: "Demonstrate how a named project objective, funding trail and evidence record will appear.",
    result: "Illustrative result only · replace with an audited project outcome.",
    contribution: "CHF 4,800 · simulated",
    status: "active",
    image: "/media/v4/impact-hands-editorial.webp",
  },
];

