import { PageHero, requireLocale, routeMetadata, styles, type LocaleParams } from "../editorial";

export const metadata = routeMetadata("About", "The intended ROOSA brand, company and impact-partner story, with unapproved details clearly marked.");

export default async function AboutPage({ params }: { params: LocaleParams }) {
  await requireLocale(params);
  return <main className={styles.page}>
    <PageHero eyebrow="About ROOSA" title="An everyday object, made impossible to ignore." lead="ROOSA pairs a distinctive pink household product with an ambition to support accountable child-protection work. This page separates the approved idea from details still awaiting review." image="/media/journal/field-team.jpg" imageAlt="A ROOSA team member delivering pink paper" />
    <section className={`${styles.section} ${styles.sectionPink}`}><div className={`${styles.sectionInner} ${styles.feature}`}><div><p className="eyebrow">Origin</p><h2>The story starts with a simple question.</h2></div><div><p>[APPROVED_ORIGIN_STORY]</p><p>The final account should name dates, decisions and people only after company review.</p></div></div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.grid2}><article className={styles.card}><p className="eyebrow">Founder</p><h3>[FOUNDER_NAME]</h3><p>[APPROVED_FOUNDER_BIOGRAPHY]</p></article><article className={styles.card}><p className="eyebrow">Why pink</p><h3>A visible break from the category.</h3><p>[APPROVED_COLOUR_RATIONALE] Product safety and material claims remain part of the product specification, not the brand story.</p></article></div></div></section>
    <section className={`${styles.section} ${styles.sectionImpact}`}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Why child protection</p><div><h2>Care needs structure, not sentiment alone.</h2><p>[APPROVED_CHILD_PROTECTION_RATIONALE] ROOSA will avoid exposing children’s identities, sensationalising harm or using unverified beneficiary claims.</p></div></div></div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Company structure</p><div><h2>Who does what.</h2><p>Names and contractual relationships below remain placeholders until legal and operational approval.</p></div></div><div className={styles.grid4}><article className={styles.card}><p className="eyebrow">Consumer brand</p><h3>ROOSA</h3><p>Product, customer experience and public reporting.</p></article><article className={styles.card}><p className="eyebrow">Operating company</p><h3>[OPERATING_COMPANY]</h3><p>Commercial operations, accounting and supplier relationships.</p></article><article className={styles.card}><p className="eyebrow">Impact partner</p><h3>[IMPACT_PARTNER]</h3><p>Approved programme delivery and project documentation.</p></article><article className={styles.card}><p className="eyebrow">Distribution</p><h3>[DISTRIBUTION_PARTNERS]</h3><p>Wholesale, fulfilment and regional availability.</p></article></div></div></section>
    <section className={`${styles.section} ${styles.sectionDark}`}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Values</p><div><h2>Useful standards for daily decisions.</h2></div></div><div className={styles.grid3}>{[["Specificity","Make claims with a period, source and owner."],["Dignity","Protect people before promoting stories."],["Accountability","Publish what can be supported and correct what changes."]].map(([title,body]) => <article className={`${styles.card} ${styles.darkCard}`} key={title}><h3>{title}</h3><p>{body}</p></article>)}</div></div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.grid2}><div><p className="eyebrow">Team</p><h2 className="heading-xl">[TEAM_PROFILES]</h2><p className={styles.placeholder}>Names, roles and portraits await consent and company approval.</p></div><div><p className="eyebrow">Timeline</p><ul className={styles.list}><li><span>[YEAR]</span><strong>[FOUNDING_MILESTONE]</strong></li><li><span>[YEAR]</span><strong>[PRODUCT_MILESTONE]</strong></li><li><span>[YEAR]</span><strong>[IMPACT_MILESTONE]</strong></li></ul></div></div></div></section>
  </main>;
}
