import { ContactForm } from "@/components/v2-editorial/ContactForm";
import { PageHero, requireLocale, routeMetadata, styles, type LocaleParams } from "../editorial";

export const metadata = routeMetadata("B2B", "ROOSA wholesale and workplace enquiries for retailers, hospitality, offices and distributors.");

export default async function B2BPage({ params }: { params: LocaleParams }) {
  await requireLocale(params);
  return <main className={styles.page}>
    <PageHero eyebrow="ROOSA for business · demo enquiry" title="Make the quietest room more memorable." lead="For retailers, offices, hotels, restaurants, distributors and corporate buyers. The demo uses the authentic Carsten Stahl pack and illustrates a Swiss quotation flow." image="/media/products/pink-pack.jpg" imageAlt="Original ROOSA pink toilet paper pack featuring Carsten Stahl" />
    <section className={`${styles.section} ${styles.sectionPink}`}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Who it is for</p><div><h2>Stock it, serve it, or make it part of the workplace.</h2></div></div><div className={styles.grid3}>{["Retailers","Offices","Hotels","Restaurants","Distributors","Corporate buyers"].map((name) => <article className={styles.card} key={name}><h3>{name}</h3><p>Original eight-roll packs, demo case quantities and tailored enquiry support.</p></article>)}</div></div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Commercial outline · demo values</p><div><h2>Useful details before an enquiry.</h2><p>These simulated values make the flow testable and will be replaced by signed commercial terms.</p></div></div><dl className={styles.details}><div className={styles.detail}><dt>Pack format</dt><dd>8-roll original ROOSA pack</dd></div><div className={styles.detail}><dt>Minimum order</dt><dd>6 cases · demo value</dd></div><div className={styles.detail}><dt>Delivery region</dt><dd>Switzerland · demo scope</dd></div><div className={styles.detail}><dt>Lead time</dt><dd>5–10 working days · demo value</dd></div><div className={styles.detail}><dt>Retail presentation</dt><dd>Original campaign pack with Carsten Stahl</dd></div><div className={styles.detail}><dt>Impact receipt</dt><dd>Partner, period and allocation fields included in the demo</dd></div></dl></div></section>
    <section className={`${styles.section} ${styles.sectionDark}`}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Partnership</p><div><h2>A distinctive product with evidence in view.</h2><p>Partner logos and the original campaign remain visible; final margin and territory terms belong in a private quotation.</p></div></div><div className={`${styles.placeholder} ${styles.darkCard}`}>Demo enquiry only · no commercial offer is created or transmitted.</div></div></section>
    <section className={styles.section}><div className={styles.sectionInner}><div className={styles.sectionHeader}><p className="eyebrow">Enquiry</p><div><h2>Tell us what your business needs.</h2><p>This demo collects only the information needed to understand a business enquiry and does not transmit or store it.</p></div></div><ContactForm variant="b2b" /></div></section>
  </main>;
}
